baseURL = 'https://wurzerloesung.github.io'
theme = 'risotto'
title = 'RootBots'
author = "FLL Team ROOTBOTS"
copyright = "© [ROOTBOTS](https://wurzerloesung.github.io/RootbotsPage)"
paginate = 3
languageCode = 'en'
DefaultContentLanguage = "en"
enableInlineShortcodes = true

ignoreErrors = true

sectionPagesMenu = "main"

[params]
    noindex = false

# Sidebar: about/bio
[params.about]
title = "ROOTBOTS"
description = "FLL Team since 2012"

[Permalinks]
    posts = "/:filename/"
[menu]

  [[menu.main]]

    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 10

[taxonomies]
category = "categories"
tag = "tags"
series = "series"

# For hugo >= 0.60.0, enable inline HTML
[markup.goldmark.renderer]
unsafe = true

[markup]

  # Table of contents
  # Add toc = true to content front matter to enable
  [markup.tableOfContents]
    startLevel = 2
    endLevel   = 3
    ordered    = true

[sections]
  [sections.post]
    type = "posts"
    id = "post"
    title = "Meine Beiträge"
    contents = ["research.md"]
