baseURL = 'https://wurzerloesung.github.io'
theme = 'risotto'
title = 'RootBots'
author = "FLL Team ROOTBOTS"
copyright = "© [ROOTBOTS](https://wurzerloesung.github.io/RootbotsPage)"
paginate = 3
languageCode = 'en'
DefaultContentLanguage = "en"
enableInlineShortcodes = true

ignoreErrors = true

sectionPagesMenu = "main"

[params]
    noindex = false

# Sidebar: about/bio
[params.about]
title = "ROOTBOTS"
description = "FLL Team since 2012"

[Permalinks]
    post = "/:filename/"
