baseURL = 'https://wurzerloesung.github.io'
theme = 'risotto'
title = 'RootBots'
author = "FLL Team ROOTBOTS"
copyright = "© [ROOTBOTS](https://wurzerloesung.github.io/RootbotsPage)"
languageCode = 'de'
defaultContentLanguage = "de"
defaultContentLanguageInSubdir = true
enableInlineShortcodes = true

ignoreErrors = true

#sectionPagesMenu = "main"

[languages]
  [languages.de]
    contentDir = 'content/de'
    languageCode = 'de-AT'
    languageName = 'de-AT'
    weight = 1

[pagination]
pagerSize = 3

[imaging]
  anchor = 'Smart'
  bgColor = '#ffffff'
  hint = 'photo'
  quality = 75
  resampleFilter = 'box'


[params]
    noindex = false

# Sidebar: about/bio
[params.about]
title = "ROOTBOTS"
description = "FLL Team since 2012"

[[params.socialLinks]]
icon = "fa-brands fa-instagram"
title = "Instagram"
url = "https://www.instagram.com/rootbots_keimgasse/"

[[params.socialLinks]]
icon = "fa-solid fa-envelope"
title = "Email"
url = "mailto:rootbots@keimgasse.at"

[Permalinks]
    posts = "/:filename/"

[menu]
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "about/"
    weight = 10

  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "posts/"
    weight = 20

  [[menu.main]]
    identifier = "sponsoring"
    name = "Sponsoring"
    url = "sponsoring/"
    weight = 30

[taxonomies]
category = "categories"
tag = "tags"
series = "series"

# For hugo >= 0.60.0, enable inline HTML
[markup.goldmark.renderer]
unsafe = true

[markup]

  # Table of contents
  # Add toc = true to content front matter to enable
  [markup.tableOfContents]
    startLevel = 2
    endLevel   = 3
    ordered    = true

[sections]
  [sections.post]
    type = "posts"
    id = "post"
    title = "Meine Beiträge"
    contents = ["research.md"]
